"""One-time migration from the reviewed profile to a complete static website."""
from pathlib import Path
from bs4 import BeautifulSoup
import html, subprocess, tempfile
OUT=Path(__file__).resolve().parents[1]
OLD=Path(tempfile.mkdtemp())
BASELINE='99b98331ab6c9e7f057d5a769ebc4892505689bf'
for filename in ['index.html','publications.html']:
    (OLD/filename).write_bytes(subprocess.check_output(['git','show',BASELINE+':'+filename],cwd=OUT))
FONT='https://cdn.prod.website-files.com/667a10df2ea8d55c5f903748/667a13fe587f6a3229bc0dd5_Manrope-VariableFont_wght.ttf'
SCHOLAR='https://scholar.google.com/citations?hl=en&user=AkzytG8AAAAJ'
SUPPORT='https://www.nature.com/articles/s41592-023-02005-8'
MEMRISTOR='https://www.nature.com/articles/s41928-024-01318-6'
UBSN='https://doi.org/10.1109/WACV61041.2025.00135'
REALS='https://doi.org/10.1109/WACV56688.2023.00198'
FIGURE='https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41592-023-02005-8/MediaObjects/41592_2023_2005_Fig1_HTML.png'
ARROW='<svg viewBox="0 0 16 16" aria-hidden="true"><path d="M3 13 13 3M3 3h10v10"/></svg>'
def link(href,text,kind='text-link'):
    external=href.startswith('https:')
    return f'<a class="{kind}" href="{html.escape(href,quote=True)}"'+(' target="_blank" rel="noopener noreferrer"' if external else '')+f'>{text}<span class="arrow">{ARROW}</span></a>'
def feature(title,text,href,cls=''):
    return f'<a class="feature-link {cls}" href="{href}"><h2>{title}</h2><p>{text}</p><span class="arrow square">{ARROW}</span></a>'
NAV=[('Research',[('index.html','Home'),('vision.html','Vision'),('research.html','Our Science'),('publications.html','Publications'),('resources.html','Resources')]),('About',[('profile.html','Seungjae Han, PhD'),('profile.html#education','Education'),('profile.html#fellowships','Fellowships'),('profile.html#service','Professional Service')]),('Updates',[('news.html','News'),('publications.html#support','SUPPORT'),('publications.html#memristor','Analogue Computing'),('https://github.com/SteveJayH','GitHub')]),('Contact',[('contact.html','Contact'),('mailto:jay0118@kaist.ac.kr','Email'),(SCHOLAR,'Google Scholar'),('CV_SeungjaeHan_0707.pdf','Curriculum Vitae')])]
wordmark='<a class="wordmark" href="index.html" aria-label="Seungjae Han, home"><span><strong>SEUNGJAE</strong> HAN</span><small>KAIST · ELECTRICAL ENGINEERING</small></a>'
header='<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container navigation-bar">'+wordmark+'<details class="navigation"><summary class="menu-toggle" aria-label="Navigation menu" aria-controls="site-navigation"><span class="menu-lines" aria-hidden="true"><i></i><i></i><i></i></span></summary><nav class="menu-panel" id="site-navigation" aria-label="Main navigation"><div class="container menu-grid">'+''.join('<div><h2>'+title+'</h2>'+''.join(link(href,txt) for href,txt in items)+'</div>' for title,items in NAV)+'</div></nav></details></div></header>'
footer='<footer class="site-footer"><div class="container footer-grid"><div>'+wordmark+'<p>School of Electrical Engineering<br>KAIST, South Korea</p></div><nav class="footer-pages" aria-label="Footer navigation">'+''.join(f'<a href="{href}">{name}</a>' for href,name in [('index.html','Home'),('vision.html','Vision'),('research.html','Research'),('profile.html','About'),('publications.html','Publications'),('resources.html','Resources'),('news.html','News'),('contact.html','Contact')])+'</nav><div class="footer-links">'+link('mailto:jay0118@kaist.ac.kr','Email')+link(SCHOLAR,'Google Scholar')+link('CV_SeungjaeHan_0707.pdf','CV')+'</div></div></footer>'
def page(name,title,body,description):
    doc=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#982b34"><title>{title} | Seungjae Han</title><meta name="description" content="{html.escape(description,quote=True)}"><link rel="canonical" href="https://stevejayh.github.io/{'' if name=='index' else name+'.html'}"><link rel="preconnect" href="https://cdn.prod.website-files.com" crossorigin><link rel="preload" href="{FONT}" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="assets/site.css"><script src="assets/site.js" defer></script></head>
<body data-page="{name}">{header}<main id="main" tabindex="-1">{body}</main>{footer}</body></html>'''
    (OUT/f'{name}.html').write_text(doc)
def hero(eyebrow,title,desc='',extra=''):
    return '<section class="page-hero"><div class="container"><div class="hero-copy">'+(f'<p class="eyebrow">{eyebrow}</p>' if eyebrow else '')+f'<h1>{title}</h1>'+(f'<p class="hero-description">{desc}</p>' if desc else '')+extra+'</div></div></section>'
def figure():
    return f'<figure class="science-figure"><a href="{SUPPORT}" target="_blank" rel="noopener noreferrer"><img src="{FIGURE}" width="1200" height="1100" loading="lazy" alt="SUPPORT architecture and examples of denoising voltage imaging data, from Figure 1 of the 2023 paper."></a><figcaption>Eom, Han, Park et al., <a href="{SUPPORT}">Nature Methods (2023), Fig. 1</a>. <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.</figcaption></figure>'
home=hero('','Developing self-supervised learning methods to recover neural activity from fluorescence microscopy data.','I am Seungjae Han, a postdoctoral fellow at KAIST. I develop computational methods for neuroscience, working on self-supervised learning, image reconstruction, and the analysis of neural recordings.',link('research.html','Learn More','button-link'))
home+='<section class="section" id="vision"><div class="container split vision-split"><div><p class="eyebrow">Vision</p><h2 class="section-title">Connecting how images are acquired with how neural signals are recovered.</h2><p class="body-copy">My work brings together statistical estimation, machine learning, and fluorescence microscopy. The aim is to make neural activity measurements more reliable without requiring clean training images.</p>'+link('vision.html','Read the Vision','button-link')+'</div>'+figure()+'</div></section>'
home+='<section class="section purple" id="research"><div class="container split"><figure class="cover-figure"><a href="publications.html#support"><img src="nature_methods_cover.png" width="425" height="584" loading="lazy" alt="Nature Methods, October 2023 cover featuring SUPPORT."></a><figcaption>Nature Methods · October 2023</figcaption></figure><div><p class="eyebrow">Research</p><h2 class="section-title">Recovering fast signals from noisy data, and designing the algorithms that make this possible.</h2><p class="body-copy">Research topics include voltage imaging denoising, calcium imaging analysis, and self-supervised processing on analogue hardware.</p>'+link('research.html','Learn More','button-link')+'</div></div></section>'
home+='<section class="section gray" id="impact"><div class="container"><p class="eyebrow">Impact</p><div class="impact-grid"><article><h2 class="section-title">Denoising without losing fast neural dynamics.</h2><p>SUPPORT uses spatial and temporal information to denoise voltage imaging recordings.</p>'+link('publications.html#support','Nature Methods · 2023')+'</article><article><h2 class="section-title">Self-supervised processing on analogue hardware.</h2><p>A memristor-array platform combines video processing with self-calibration.</p>'+link('publications.html#memristor','Nature Electronics · 2025')+'</article></div></div></section>'
home+='<section class="section"><div class="container feature-grid">'+feature('Research','Methods for denoising, reconstruction, and the analysis of neural recordings.','research.html')+feature('About','Biography, education, appointments, fellowships, and academic service.','profile.html','teal')+feature('Publications','Journal articles, conference papers, and preprints.','publications.html','purple')+'</div></section>'
page('index','Home',home,'Seungjae Han at KAIST. Computational neuroscience, self-supervised learning, and fluorescence microscopy.')
vision=hero('Vision','Reliable measurements of neural activity.','I develop computational methods for neuroscience, with a focus on self-supervised learning and fluorescence microscopy.')
vision+='<section class="section"><div class="container split"><div><p class="eyebrow">Research direction</p><h2 class="section-title">Treating acquisition and analysis as parts of the same problem.</h2><p class="body-copy">My work spans algorithms and imaging pipelines. I am interested in methods that recover useful signals from the data an experiment can actually collect, rather than assuming that ideal training data are available.</p><p class="body-copy">This connects my work on voltage and calcium imaging with self-supervised network design and analogue video processing.</p>'+link('research.html','Research projects','button-link')+'</div>'+figure()+'</div></section>'
vision+='<section class="section gray"><div class="container"><p class="eyebrow">Focus</p><div class="impact-grid"><article><h2 class="section-title">Preserve the signal of interest.</h2><p>The goal is not only a cleaner image, but an accurate account of the activity that the image represents.</p></article><article><h2 class="section-title">Make methods useful in practice.</h2><p>I work on computational approaches that can be connected to experimental data and imaging workflows.</p></article></div></div></section><section class="section"><div class="container feature-grid two">'+feature('Research','See the methods and publications behind this direction.','research.html')+feature('Contact','Get in touch about research and scientific discussions.','contact.html','teal')+'</div></section>'
page('vision','Vision',vision,'Research direction: computational tools for reliable neural activity measurements.')
research=hero('What I do','Computational methods for neuroscience and imaging.','My research focuses on recovering information from noisy recordings and designing self-supervised methods that work with experimental data.')
research+='<section class="section"><div class="container split">'+figure()+'<div><p class="eyebrow">Approach</p><h2 class="section-title">Statistical models and neural networks, developed around the measurement.</h2><div class="numbered-point"><span>01</span><p>Use the spatial and temporal structure in imaging data to recover neural signals.</p></div><div class="numbered-point"><span>02</span><p>Design learning algorithms around the constraints of real data and computing hardware.</p></div></div></div></section>'
questions=[('denoising','How can fast neural activity be recovered without clean training images?'),('calcium','How can motion and neural activity be separated in calcium imaging?'),('learning','How can self-supervised methods become more computationally efficient?')]
research+='<section class="section gray"><div class="container"><p class="eyebrow blue-text">Key questions</p><div class="question-grid">'+''.join(f'<a class="question" href="research.html#{id}"><span class="eyebrow">0{i+1}</span><h2 class="section-title">{text}</h2><span class="arrow square">{ARROW}</span></a>' for i,(id,text) in enumerate(questions))+'</div></div></section>'
research+='<section class="section"><div class="container project-list"><article class="project" id="denoising"><div><p class="eyebrow blue-text">Self-supervised denoising</p><h2>Recovering neural activity</h2></div><div><h3>SUPPORT</h3><p>SUPPORT predicts a pixel from its spatial and temporal neighbours, excluding the target pixel. This allows voltage imaging data to be denoised without assuming that a fast event is present in adjacent frames.</p>'+link(SUPPORT,'Read the paper')+link('resources.html#support-code','Code and data')+'<h3>Multi-scale blind-spot networks</h3><p>U-BSN uses a U-Net-based architecture with design principles for J-invariant self-supervised denoising.</p>'+link(UBSN,'WACV 2025 paper')+'</div></article>'
research+='<article class="project" id="calcium"><div><p class="eyebrow blue-text">Calcium imaging</p><h2>Alignment and signal extraction</h2></div><div><h3>REALS</h3><p>REALS performs image alignment together with low-rank and sparse decomposition, separating motion from changing neuronal activity.</p>'+link(REALS,'WACV 2023 paper')+'<h3>Neural approximations of robust PCA</h3><p>Related work studies efficient neural-network approximations for automated calcium imaging analysis.</p>'+link('publications.html#robust-pca','MICCAI 2021 publication')+'</div></article>'
research+='<article class="project" id="learning"><div><p class="eyebrow blue-text">Learning and hardware</p><h2>Self-supervised video processing</h2></div><div><h3>Analogue computing</h3><p>This work implements self-supervised video processing with self-calibration on a selector-less memristor array.</p>'+link(MEMRISTOR,'Nature Electronics · 2025')+'<p class="body-copy">The connection between network design and computational cost also motivates the multi-scale denoising work.</p>'+link(UBSN,'Multi-scale network design')+'</div></article></div></section>'
research+='<section class="section gray"><div class="container feature-grid two">'+feature('Publications','Read the complete publication list.','publications.html')+feature('Resources','Software and datasets associated with the research.','resources.html','teal')+'</div></section>'
page('research','Research',research,'Research on SUPPORT, calcium imaging analysis, blind-spot networks, and analogue video processing.')
old=BeautifulSoup((OLD/'index.html').read_text(),'html.parser')
profile=old.main.decode_contents().replace('href="index.html','href="profile.html')
profile=profile.replace('<a class="text-link" href="mailto:jay0118@kaist.ac.kr">Contact','<a class="text-link" href="contact.html">Contact')
profile=profile.replace('<div class="profile-links">','<div class="profile-links">'+link('research.html','Research'))
page('profile','Seungjae Han, PhD',profile,'Biography, education, appointments, fellowships, awards, and professional service.')
pubs=BeautifulSoup((OLD/'publications.html').read_text(),'html.parser')
ids=['abunmix','event-imaging','memristor','expansion','ubsn','optical-clearing','pixels','support','zebrafish','reals','impasto','refocusing','robust-pca','3dm','lte','haptic']
assert len(pubs.select('.publication'))==len(ids)
items=[]
for id,p in zip(ids,pubs.select('.publication')):
    year=p.find_parent(class_='publication-year').get('id').split('-')[-1]
    a=p.select_one('.article-link')
    if id=='ubsn':a['href']=UBSN
    if id=='reals':a['href']=REALS
    authors=str(p.select_one('.authors'));venue=p.select_one('.venue').get_text();note=p.select_one('.publication-note')
    href=a.get('href');label='Find on Scholar' if 'scholar.google.com/scholar?' in href else 'View paper'
    items.append(f'<li class="publication" id="{id}" data-year="{year}"><div><h2>{html.escape(p.h3.get_text())}</h2>{authors}<p class="publication-venue"><span>{year}</span> <a href="{html.escape(href,quote=True)}" target="_blank" rel="noopener noreferrer">{html.escape(venue)}</a></p>'+(f'<p class="publication-note">{html.escape(note.get_text())}</p>' if note else '')+f'</div><a class="paper-action" href="{html.escape(href,quote=True)}" aria-label="{label}: {html.escape(p.h3.get_text(),quote=True)}" target="_blank" rel="noopener noreferrer"><span class="arrow square">{ARROW}</span></a></li>')
years=['2026','2025','2024','2023','2022','2021','2019','2018']
selector='<div class="year-picker"><label for="paper-year">Publications by year</label><select id="paper-year" aria-label="Publication year"><option value="all">All years</option>'+''.join(f'<option>{y}</option>' for y in years)+'</select></div>'
publications=hero('Research','Publications','',selector)+'<section class="section"><div class="container"><p class="author-note">* Equal contribution · ** Co-corresponding authors</p><p class="sr-only" id="publication-count" aria-live="polite">16 publications</p><ol class="publication-list">'+''.join(items)+'</ol></div></section>'
page('publications','Publications',publications,'Journal articles, conference papers, and preprints by Seungjae Han.')
resources=hero('Research','Resources','Code, data, and links for working with the published methods.')
resources+='<section class="section"><div class="container resource-list"><article id="support-code"><p class="eyebrow blue-text">Software</p><h2>SUPPORT</h2><p>The PyTorch implementation, installation instructions, and examples for SUPPORT.</p>'+link('https://github.com/NICALab/SUPPORT','Code and documentation','button-link')+'</article><article><p class="eyebrow blue-text">Data</p><h2>SUPPORT datasets</h2><p>Public imaging datasets accompanying the Nature Methods paper.</p>'+link('https://zenodo.org/records/8176722','Datasets on Zenodo','button-link')+'</article><article><p class="eyebrow blue-text">Publications</p><h2>Papers and supplementary material</h2><p>Publisher pages provide the articles and their associated supplementary files.</p>'+link('publications.html','Publication list','button-link')+'</article></div></section>'
page('resources','Resources',resources,'SUPPORT software, documentation, and public imaging datasets.')
news=hero('Updates','News')+'<section class="section"><div class="container news-page">'+''.join(str(item) for item in old.select('.news-item'))+'</div></section><section class="section gray"><div class="container feature-grid two">'+feature('Publications','Browse the work behind the research updates.','publications.html')+feature('About','Full academic background and awards.','profile.html','teal')+'</div></section>'
page('news','News',news,'Research news, awards, and fellowships from Seungjae Han.')
contact=hero('Contact','Get in touch.')+'<section class="section"><div class="container contact-grid"><div><h2>Seungjae Han, PhD</h2><p>Postdoctoral Fellow<br>School of Electrical Engineering<br>KAIST, South Korea</p>'+link('mailto:jay0118@kaist.ac.kr','jay0118@kaist.ac.kr','button-link')+'</div><div><p class="eyebrow blue-text">Research and background</p>'+link(SCHOLAR,'Google Scholar','contact-row')+link('https://github.com/SteveJayH','GitHub','contact-row')+link('CV_SeungjaeHan_0707.pdf','Curriculum Vitae','contact-row')+link('profile.html','Biography','contact-row')+'</div></div></section>'
page('contact','Contact',contact,'Contact Seungjae Han, School of Electrical Engineering, KAIST.')
css=subprocess.check_output(['git','show',BASELINE+':assets/site.css'],cwd=OUT).decode()
css=css.replace('"Manrope Reference", "Manrope"','"Manrope"').replace('"Manrope Reference"','"Manrope"').replace('--blue: #21166c;','--blue: #1b1464;').replace('--width: 1280px;','--width: 1280px;\n  --teal: #1f4b51;\n  --charcoal: #343a40;')
(OUT/'assets/site.css').write_text(css+'\n'+(OUT/'tools/site-additions.css').read_text())
print('Generated eight static pages and shared styles, retaining all 16 publication records.')
